### ISSUE TITLE
(breakpoint mode) compile the code behind breakpoint

### ISSUE THREAD

**Issue by aminya** [JuliaDebug/JuliaInterpreter.jl#298]
I am not how practical this is or if it is done already
To speed up the debugging, is it possible to compile the code before the breakpoint specified by line number? and if the breakpoint is inside a control flow (such as if, while, for, etc.) the compilation should be done until before the control loop.

![Image](https://user-images.githubusercontent.com/16418197/60684639-895cf680-9e64-11e9-99df-3fa6672eff68.jpg)

I am assuming to achieve this, a new debugger mode which is only meant for hitting the breakpoints is needed.

**Comment by KristofferC** [comment]
Breakpoints needs to be addable, removable, modifiable while the code is running, otherwise you could just insert some hook directly into the source code

Please see https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/204 for some more discussion about different approaches to improving performance.

**Comment by aminya** [comment]
Well, that is exactly what I want. Just to check the values of the variables inside workspace (especially if the code is inside a function).
As I said, this is going to be a new mode of debugging just for breakpoints. After checking the values of the variables, if users press continues (they might remove the breakpoint), the debugger should scan the rest of the code to see if there are new breakpoints there.

**Comment by KristofferC** [comment]
> Just to check the values of the variables inside workspace (especially if the code is inside a function).

A feature could be added to Debugger.jl / Juno debugger that allows you to insert some macro and gives you an interactive thing with the local variables (using `Base.@locals`). It won't be much more than a pretty printer though since you can't do any stepping etc. But if that is what you need, it should be fairly easy to implement,

**Comment by aminya** [comment]
Isn't it possible to compile part of the code and call the interpreter/debugger after that?
 As I said, ideally, after checking the values of the variables, if users press continues, the debugger should scan the rest of the code to see if there are new breakpoints there.
Also, the user may want to run some mini test codes using the variable values until that moment.

**Comment by pfitzseb** [comment]
Feel free to give https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/297#issuecomment-502429542 a go, we might get around to adding that to Debugger.jl/Juno at some point.

**Comment by aminya** [comment]
> 
> 
> Feel free to give [#297 (comment)](https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/297#issuecomment-502429542) a go, we might get around to adding that to Debugger.jl/Juno at some point.

@pfitzseb Thank you! should I create an issue there?
