### ISSUE TITLE
Provide a method to run a file in the debugger

### ISSUE THREAD

**Issue by davidanthoff** [JuliaDebug/JuliaInterpreter.jl#361]
I've tried `JuliaInterpreter.@interpret include("foo.jl")` but that doesn't end up running the content of `foo.jl` in the debugger.

Ideally it would just be a function like `run_file_in_interpreter(filename)`.

This is where I'm stuck right now for the VS Code integration.

**Comment by davidanthoff** [comment]
Actually, to clarify: it does run, but breakpoints don't seem to work. I have a file called `main.jl`:
```julia
function foo()
    println("STEP 1")
    println("STEP 2")
    println("STEP 3")
end

foo()
```

Then I set a breakpoint on line 3 in this file with `breakpoint(fullfilename, 3)`, and then I runrun `@interpret include(main.jl)`. I get the output from the `println` statements, but it never breaks.

**Comment by timholy** [comment]
The problem is that `include` eventually resolves to a [ccall](https://github.com/JuliaLang/julia/blob/fbc2c0aec19a7c415011c1abd4f05622ac9c41e7/base/boot.jl#L329) which "leaves" the interpreter. This is presumably fixable if we:
- `str = read(filename, String)`
- iteratively `Meta.parse` `str`, until we get to the end of the file, appending each expression to the args of a `:toplevel` expression.
- Call `JuliaInterpreter.split_expressions` on the result
- interpret and/or `eval` our way through these expressions

Since this is a fair amount of work and I'm not sure where this comes up, let me ask: what's the context in which you need this `include` functionality? I don't think it comes up in Juno, though I could be wrong.

**Comment by KristofferC** [comment]
I think the end goal is to be able to debug top-level just like functions.

**Comment by davidanthoff** [comment]
Yeah, the goal here is simply to implement F5 ("debug the currently open file") in VS Code. So I don't actually need to be able to debug `include` (i.e. that was not a good starting point for my issue), I really just need a function equivalent to `finish_and_return!` that I can pass a filename to and then that runs in the debugger until a breakpoint hits.

**Comment by davidanthoff** [comment]
So I think the ideal API from my end would be that I can have a function `prepare_global_frame(filename)` (not sure that is a sensible name), and that returns something that I can pass directly to `debug_command`. I would imagine that the stepper would only step over actual code that does something then, not definitions (like type definitions or function/method declarations).

**Comment by timholy** [comment]
`JuliaInterpreter.split_expressions` is probably what you want. See the tests in `toplevel.jl` for numerous examples.

**Comment by davidanthoff** [comment]
Same here, all working now!
