### ISSUE TITLE
MWE of failure in Random

### ISSUE THREAD

**Issue by macd** [JuliaDebug/JuliaInterpreter.jl#99]
So ```rand!``` should be non allocating.  This fails in the interpreter.

```
ex = quote
    A = [0.0, 0.0]
    @test @allocated(rand!(A)) == 0
end
```

**Comment by timholy** [comment]
My suspicion is that this one is not fixable, unfortunately---the interpreter itself allocates due to boxing from type-instability (which is probably an unavoidable problem with an interpreter). I think lots of tests will fail for this reason.

Let's leave this open, though, because certainly someone should go through carefully and make sure we allocate as little as possible (and I haven't done that yet).

**Comment by KristofferC** [comment]
Yes, queries about the exact state of how things got executed will not work and I don't think there is a plan for it to work.
